package com.wallet.project.ui.theme

import androidx.compose.ui.graphics.Color

val walletLightPrimary = Color(0xFF2962FF)
val walletLightOnPrimary = Color(0xFFFFFFFF)
val walletLightPrimaryContainer = Color(0xFF758FFF)
val walletLightOnPrimaryContainer = Color(0xFF000000)
val walletLightSecondary = Color(0xFF00E5FF)
val walletLightOnSecondary = Color(0xFF000000)
val walletLightSecondaryContainer = Color(0xFF73E8FF)
val walletLightOnSecondaryContainer = Color(0xFF000000)
val walletLightTertiary = Color(0xFFFFD600)
val walletLightOnTertiary = Color(0xFF000000)
val walletLightTertiaryContainer = Color(0xFFFFE352)
val walletLightOnTertiaryContainer = Color(0xFF000000)
val walletLightError = Color(0xFFB00020)
val walletLightErrorContainer = Color(0xFFFCD8D8)
val walletLightOnError = Color(0xFFFFFFFF)
val walletLightOnErrorContainer = Color(0xFF370000)
val walletLightBackground = Color(0xFFFFFBFE)
val walletLightOnBackground = Color(0xFF1C1B1F)
val walletLightSurface = Color(0xFFFFFBFE)
val walletLightOnSurface = Color(0xFF1C1B1F)
val walletLightSurfaceVariant = Color(0xFFE7E0EC)
val walletLightOnSurfaceVariant = Color(0xFF49454F)
val walletLightOutline = Color(0xFF79747E)
val walletLightInverseOnSurface = Color(0xFFF2E1F8)
val walletLightInverseSurface = Color(0xFF313033)
val walletLightPrimaryInverse = Color(0xFFB3C1FF)

val walletDarkPrimary = Color(0xFF2962FF)
val walletDarkOnPrimary = Color(0xFFFFFFFF)
val walletDarkPrimaryContainer = Color(0xFF0044C8)
val walletDarkOnPrimaryContainer = Color(0xFFFFFFFF)
val walletDarkSecondary = Color(0xFF00E5FF)
val walletDarkOnSecondary = Color(0xFF000000)
val walletDarkSecondaryContainer = Color(0xFF01879D)
val walletDarkOnSecondaryContainer = Color(0xFFFFFFFF)
val walletDarkTertiary = Color(0xFFFFD600)
val walletDarkOnTertiary = Color(0xFF000000)
val walletDarkTertiaryContainer = Color(0xFFC7A500)
val walletDarkOnTertiaryContainer = Color(0xFFFFFFFF)
val walletDarkError = Color(0xFFCF6679)
val walletDarkErrorContainer = Color(0xFFB00020)
val walletDarkOnError = Color(0xFFFFFFFF)
val walletDarkOnErrorContainer = Color(0xFF370000)
val walletDarkBackground = Color(0xFF121212)
val walletDarkOnBackground = Color(0xFFFFFFFF)
val walletDarkSurface = Color(0xFF121212)
val walletDarkOnSurface = Color(0xFFFFFFFF)
val walletDarkSurfaceVariant = Color(0xFF434343)
val walletDarkOnSurfaceVariant = Color(0xFFFFFFFF)
val walletDarkOutline = Color(0xFF79747E)
val walletDarkInverseOnSurface = Color(0xFFEDE7F6)
val walletDarkInverseSurface = Color(0xFF1F1A24)
val walletDarkPrimaryInverse = Color(0xFF8A9EFF)
val successColor = Color(0xFF6DC070)
