package com.stori.challenge.ui.theme

import androidx.compose.ui.graphics.Color

val storiLightPrimary = Color(0xFF2962FF)
val storiLightOnPrimary = Color(0xFFFFFFFF)
val storiLightPrimaryContainer = Color(0xFF758FFF)
val storiLightOnPrimaryContainer = Color(0xFF000000)
val storiLightSecondary = Color(0xFF00E5FF)
val storiLightOnSecondary = Color(0xFF000000)
val storiLightSecondaryContainer = Color(0xFF73E8FF)
val storiLightOnSecondaryContainer = Color(0xFF000000)
val storiLightTertiary = Color(0xFFFFD600)
val storiLightOnTertiary = Color(0xFF000000)
val storiLightTertiaryContainer = Color(0xFFFFE352)
val storiLightOnTertiaryContainer = Color(0xFF000000)
val storiLightError = Color(0xFFB00020)
val storiLightErrorContainer = Color(0xFFFCD8D8)
val storiLightOnError = Color(0xFFFFFFFF)
val storiLightOnErrorContainer = Color(0xFF370000)
val storiLightBackground = Color(0xFFFFFBFE)
val storiLightOnBackground = Color(0xFF1C1B1F)
val storiLightSurface = Color(0xFFFFFBFE)
val storiLightOnSurface = Color(0xFF1C1B1F)
val storiLightSurfaceVariant = Color(0xFFE7E0EC)
val storiLightOnSurfaceVariant = Color(0xFF49454F)
val storiLightOutline = Color(0xFF79747E)
val storiLightInverseOnSurface = Color(0xFFF2E1F8)
val storiLightInverseSurface = Color(0xFF313033)
val storiLightPrimaryInverse = Color(0xFFB3C1FF)

val storiDarkPrimary = Color(0xFF2962FF)
val storiDarkOnPrimary = Color(0xFFFFFFFF)
val storiDarkPrimaryContainer = Color(0xFF0044C8)
val storiDarkOnPrimaryContainer = Color(0xFFFFFFFF)
val storiDarkSecondary = Color(0xFF00E5FF)
val storiDarkOnSecondary = Color(0xFF000000)
val storiDarkSecondaryContainer = Color(0xFF01879D)
val storiDarkOnSecondaryContainer = Color(0xFFFFFFFF)
val storiDarkTertiary = Color(0xFFFFD600)
val storiDarkOnTertiary = Color(0xFF000000)
val storiDarkTertiaryContainer = Color(0xFFC7A500)
val storiDarkOnTertiaryContainer = Color(0xFFFFFFFF)
val storiDarkError = Color(0xFFCF6679)
val storiDarkErrorContainer = Color(0xFFB00020)
val storiDarkOnError = Color(0xFFFFFFFF)
val storiDarkOnErrorContainer = Color(0xFF370000)
val storiDarkBackground = Color(0xFF121212)
val storiDarkOnBackground = Color(0xFFFFFFFF)
val storiDarkSurface = Color(0xFF121212)
val storiDarkOnSurface = Color(0xFFFFFFFF)
val storiDarkSurfaceVariant = Color(0xFF434343)
val storiDarkOnSurfaceVariant = Color(0xFFFFFFFF)
val storiDarkOutline = Color(0xFF79747E)
val storiDarkInverseOnSurface = Color(0xFFEDE7F6)
val storiDarkInverseSurface = Color(0xFF1F1A24)
val storiDarkPrimaryInverse = Color(0xFF8A9EFF)
val successColor = Color(0xFF6DC070)
